name: Deploy to Firebase

on:
  push:
    branches:
      - master

jobs:
  deploy:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install yarn
        run: npm install -g yarn

      - name: Download dependencies
        run: yarn --frozen-lockfile

      - name: Create env
        uses: finnp/create-file-action@1.0.0
        env:
          FILE_NAME: ".env.json"
          FILE_DATA: "{\n\"BACKEND_HOST_MOCKS\": \"http://localhost:3000\",\n\"BACKEND_HOST\": \"${{ secrets.BACKEND_HOST }}\",\n\"PUBLIC_URL\": \"/public\"\n}"

      - name: Prepare for deploy
        run: yarn run predeploy

      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}